### ISSUE TITLE
Apostrof ved genitiv

### ISSUE THREAD

**Issue by gormur** [NKAmapper/addr2osm#2]
I forrige adresseprosjekt ble det brukt ekte apostof for genitiv: ’
I corrections.json er det brukt noe annet: '
Var dette er bevisst valg? Det var litt diskusjon i sist runde. Mener konklusjonen var at det var best å bruke det typografisk korrekte og ikke det som er feil men "lett tilgjengelig på tastaturet".

https://www.sprakradet.no/sprakhjelp/Skriveregler/tegn/Apostrof/

**Comment by NKAmapper** [comment]
Det er ingen spesiell korrigering for dette i programmet - Kartverkets data blir bare brukt direkte videre. Jeg er enig i at **’** er mer korrekt enn **'** for genitiv i vanlige rettskrivning/tegnsetting. Begge deler er imidlertid i vanlig bruk. Jeg har ingen sterke synspunkter og valgte den enklere **'** fordi:

- Navnene kommer slik fra Kartverket
- Veinavnene kommer også slik fra Elveg-importen (og det er de samme veinavnene som brukes i adressenodene)
- Brukere som legger inn veinavn og adressenavn manuelt bruker som regel dette enklere tegnet fordi det finnes på tastaturet
- Det er mer robust ved søk (om en eller annen app ikke skulle takle korrigere mellom de to tegnene automatisk)
- Begge tegn er i vanlig bruk for dette formålet

Jeg fant ikke noe om dette i import-wikien og gamle diskusjoner fra mail-listen er ikke så enkle å finne, og har ofte ikke noen konklusjon.
